<template>
<div class="loadingio-spinner-bars-cmuvw2z6l1r"><div class="ldio-poo6o4l4cjj">
<div></div><div></div><div></div><div></div>
</div></div>
</template>
<style>

@keyframes ldio-poo6o4l4cjj {
  0% { opacity: 1 }
  50% { opacity: .5 }
  100% { opacity: 1 }
}
.ldio-poo6o4l4cjj div {
  position: absolute;
  width: 20px;
  height: 80px;
  top: 60px;
  animation: ldio-poo6o4l4cjj 1s cubic-bezier(0.5,0,0.5,1) infinite;
}.ldio-poo6o4l4cjj div:nth-child(1) {
  transform: translate(30px,0);
  background: #e15b64;
  animation-delay: -0.6s;
}.ldio-poo6o4l4cjj div:nth-child(2) {
  transform: translate(70px,0);
  background: #f47e60;
  animation-delay: -0.4s;
}.ldio-poo6o4l4cjj div:nth-child(3) {
  transform: translate(110px,0);
  background: #f8b26a;
  animation-delay: -0.2s;
}.ldio-poo6o4l4cjj div:nth-child(4) {
  transform: translate(150px,0);
  background: #abbd81;
  animation-delay: -1s;
}
.loadingio-spinner-bars-cmuvw2z6l1r {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-poo6o4l4cjj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-poo6o4l4cjj div { box-sizing: content-box; }
/* generated by https://loading.io/ */

</style>